// src/lib/api/endpoints.ts


export const API = {
    AUTH: {
        BUYER: {
            SIGN_UP: "/api/users/buyer/sign-up",
            LOGIN: "/api/users/buyer/login",
            CHECK_USERNAME_UNIQUE: "/api/users/buyer/check-username-unique",
            GOOGLE_LOGIN: "/api/users/buyer/login-with-google",
            SEND_ACCOUNT_REGISTRATION_EMAIL: "/api/users/buyer/send-account-registration-email",
            VERIFY_ACCOUNT_REGISTRATION: "/api/users/buyer/verify-account/registration",
            FORGOT_PASSWORD: "/api/users/buyer/forgot-password",
            VERIFY_ACCOUNT_RESET_PASSWORD: "/api/users/buyer/verify-account/reset-password",
            RESET_PASSWORD: "/api/users/buyer/reset-password",
            GET_CURRENT_BUYER_USER: "/api/users/buyer/get-current-buyer",
            UPDATE_PROFILE_DETAILS: "/api/users/buyer/update-profile-details",
            UPLOAD_PROFILE_PICTURE: "/api/users/buyer/upload-profile-picture",
            DELETE_ACCOUNT: "/api/users/buyer/delete-account",
            GET_BUYER_BY_ID: "/api/users/buyer",
            GET_ALL_BUYERS: "/api/users/buyer/get-all-buyers",
        },
        SELLER: {
            SIGN_UP: "/api/users/seller/sign-up",
            LOGIN: "/api/users/seller/login",
            SEND_ACCOUNT_REGISTRATION_EMAIL: "/api/users/seller/send-account-registration-email",
            VERIFY_ACCOUNT_REGISTRATION: "/api/users/seller/verify-account-registration",
            FORGOT_PASSWORD: "/api/users/seller/forgot-password",
            RESET_PASSWORD: "/api/users/seller/reset-password",
            GET_CURRENT_SELLER_USER: "/api/users/seller/get-current-seller",
            UPDATE_PROFILE_DETAILS: "/api/users/seller/update-profile-details",
            UPLOAD_PROFILE_PICTURE: "/api/users/seller/upload-profile-picture",
            DELETE_ACCOUNT: "/api/users/seller/delete-account",
            GET_SELLER_BY_ID: "/api/users/seller",
            GET_ALL_SELLERS: "/api/users/seller/get-all-sellers",
        },
        ADMIN: {
            SIGN_UP: "/api/users/admin/sign-up",
            LOGIN: "/api/users/admin/login",
            SEND_ACCOUNT_REGISTRATION_EMAIL: "/api/users/admin/send-account-registration-email",
            VERIFY_ACCOUNT_REGISTRATION: "/api/users/admin/verify-account-registration",
            FORGOT_PASSWORD: "/api/users/admin/forgot-password",
            VERIFY_ACCOUNT_RESET_PASSWORD: "/api/users/admin/verify-account-reset-password",
            RESET_PASSWORD: "/api/users/admin/reset-password",
            LOGOUT: "/api/users/admin/logout",
            GET_CURRENT_ADMIN_USER: "/api/users/admin",
            UPDATE_PROFILE_DETAILS: "/api/users/admin/update-profile-details",
            DELETE_ACCOUNT: "/api/users/admin/delete-account",
            UPLOAD_PROFILE_PICTURE: "/api/users/admin/upload-profile-picture",
            GET_ALL_SELLERS: "/api/users/admin/get-all-sellers",
            GET_SELLER_BY_ID: "/api/users/admin/get-seller-by-id",
            CREATE_SELLER_ACCOUNT: "/api/users/admin/create-seller-account",
            UPDATE_SELLER_DETAILS: "/api/users/admin/update-seller-details",
            UPLOAD_SELLER_PROFILE_PICTURE: "/api/users/admin/upload-seller-profile-picture",
            DELETE_SELLER_ACCOUNT: "/api/users/admin/delete-seller-account",
        }
    },
    CATEGORY: {
        CREATE_CATEGORY: "/api/category/create-category",
        UPDATE_CATEGORY: "/api/category/update-category-details",
        DELETE_CATEGORY: "/api/category/delete-category",
        GET_CATEGORY_BY_ID: "/api/category",
        GET_ALL_CATEGORIES: "/api/category/get-all-categories",
    },
    PRODUCT: {
        CREATE_PRODUCT: "/api/product/create-product",
        UPDATE_PRODUCT: "/api/product/update-product-details",
        DELETE_PRODUCT: "/api/product/delete-product",
        GET_PRODUCT_BY_ID: "/api/product",
        GET_ALL_PRODUCTS: "/api/product/get-all-products",
        GET_ALL_VERIFIED_PRODUCTS: "/api/product/get-all-verified-products",
        UPDATE_PRODUCT_BY_ADMIN: "/api/product/update-product-by-admin",
    },
    PRODUCT_CONDITION: {
        CREATE_PRODUCT_CONDITION: "/api/product-condition/create-product-condition",
        UPDATE_PRODUCT_CONDITION: "/api/product-condition/update-product-condition-details",
        DELETE_PRODUCT_CONDITION: "/api/product-condition/delete-product-condition",
        GET_PRODUCT_CONDITION_BY_ID: "/api/product-condition",
        GET_ALL_PRODUCT_CONDITIONS: "/api/product-condition/get-all-product-conditions",
    },
    BID: {
        CREATE_BID: "/api/bid/create-bid",
        UPDATE_BID: "/api/bid/update-bid-details",
        DELETE_BID: "/api/bid/delete-bid",
        GET_BID_BY_ID: "/api/bid",
        GET_ALL_BIDS: "/api/bid/get-all-bids",
        // GET_ALL_BIDS_BY_PRODUCT_ID: "/api/bid/get-all-bids",
        // GET_ALL_BIDS_BY_BUYER_ID: "/api/bid/get-all-bids",
        // GET_ALL_BIDS_BY_SELLER_ID: "/api/bid/get-all-bids",
    },
    ORDER: {
        CREATE_ORDER: "/api/order/create-order",
        UPDATE_ORDER_DETAILS: "/api/order/update-order-details",
        UPDATE_ORDER_STATUS: "/api/order/update-order-status",
        DELETE_ORDER: "/api/order/delete-order",
        GET_ORDER_BY_ID: "/api/order",
        GET_ALL_ORDERS: "/api/order/get-all-orders",
        GET_ALL_ORDERS_BY_BUYER_ID: "/api/order/get-all-orders-by-buyer-id",
        GET_ALL_ORDERS_BY_SELLER_ID: "/api/order/get-all-orders-by-seller-id",
    },
    PAYMENT: {
        INITIATE_PAYMENT: "/api/payment/initiate-payment",
        FINALIZE_PAYMENT_ESEWA: "/api/payment/esewa-callback",
        FINALIZE_PAYMENT_KHALTI: "/api/payment/khalti-callback",
        UPDATE_PAYMENT_STATUS: "/api/payment/update-payment-status",
        DELETE_PAYMENT: "/api/payment/delete-payment",
        GET_PAYMENT_BY_ID: "/api/payment",
        GET_ALL_PAYMENTS: "/api/payment/get-all-payments",
        GET_ALL_PAYMENTS_BY_BUYER_ID: "/api/payment/get-all-payments-by-buyer-id",
        GET_ALL_PAYMENTS_BY_SELLER_ID: "/api/payment/get-all-payments-by-seller-id",
    },
    INVOICE: {
        GET_INVOICE_BY_ID: "/api/invoice",
        GET_INVOICE_BY_TRANSACTION_ID: "/api/invoice/get-invoice-by-transaction-id",
        GET_ALL_INVOICES: "/api/invoice/get-all-invoices",
    }
};