// src/app/layout.tsx
import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/options.ts";
import { GoogleOAuthProvider } from '@react-oauth/google';
import AuthProvider from "./context/auth-provider.tsx";
import KnockClientWrapper from '@/components/wrappers/knock-client-wrapper.tsx';
import { ThemeProvider } from "./context/theme-provider.tsx";
import ThemedToaster from "@/components/themed-toaster.tsx";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Leelame",
    description: "Generated by create next app",
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const session = await getServerSession(authOptions);

    const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
    if (!googleClientId) {
        console.error("Missing NEXT_PUBLIC_GOOGLE_CLIENT_ID in environment variables.");
    }

    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider>
                    <ThemedToaster />
                    <AuthProvider session={session}>
                        <GoogleOAuthProvider clientId={googleClientId ?? ""}>
                            <KnockClientWrapper>
                                {children}
                            </KnockClientWrapper>
                        </GoogleOAuthProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}

export default RootLayout;